// このファイルは編集画面、または手作業で編集できます。
window.EXHIBITION_DATA = {
  "rooms": [
    {
      "id": "room-01",
      "name": "物大",
      "label": "ROOM Butudai",
      "image": "images/room-01.svg",
      "alt": "白い曲線が重なる展示室の抽象ビジュアル"
    },
    {
      "id": "room-02",
      "name": "高３−１",
      "label": "ROOM H3-1",
      "image": "images/room-02.svg",
      "alt": "光と格子が交差する展示室の抽象ビジュアル"
    }
  ],
  "exhibits": [
    {
      "id": "work-01",
      "slug": "automatic-bin",
      "number": "01",
      "name": "テスラコイル",
      "roomId": "room-01",
      "order": 1,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-02",
      "slug": "transformer",
      "number": "02",
      "name": "LEDキューブ",
      "roomId": "room-01",
      "order": 2,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-03",
      "slug": "automatic-guitar",
      "number": "04",
      "name": "ホログラム",
      "roomId": "room-01",
      "order": 4,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-04",
      "slug": "lion-robot",
      "number": "05",
      "name": "トランスフォーマー",
      "roomId": "room-01",
      "order": 5,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-05",
      "slug": "pipe-organ",
      "number": "06",
      "name": "4脚ロボット",
      "roomId": "room-01",
      "order": 6,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-06",
      "slug": "house-model",
      "number": "07",
      "name": "パイプオルガン",
      "roomId": "room-01",
      "order": 7,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-07",
      "slug": "air-hockey",
      "number": "08",
      "name": "コイルガン",
      "roomId": "room-01",
      "order": 8,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-08",
      "slug": "car-racing",
      "number": "09",
      "name": "ゴミ箱ロボット",
      "roomId": "room-02",
      "order": 0,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-09",
      "slug": "magic-wand-1",
      "number": "03",
      "name": "住宅模型",
      "roomId": "room-01",
      "order": 3,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-10",
      "slug": "magic-wand-2",
      "number": "10",
      "name": "カーレース",
      "roomId": "room-02",
      "order": 1,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-11",
      "slug": "junior-games",
      "number": "11",
      "name": "イライラ棒",
      "roomId": "room-02",
      "order": 2,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-12",
      "slug": "coilgun",
      "number": "12",
      "name": "中１ゲー",
      "roomId": "room-02",
      "order": 3,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-13",
      "slug": "tesla-coil",
      "number": "13",
      "name": "エアホッケー",
      "roomId": "room-02",
      "order": 4,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    },
    {
      "id": "work-14",
      "slug": "electronics-workshop",
      "number": "14",
      "name": "自動演奏ギター",
      "roomId": "room-02",
      "order": 5,
      "summary": "",
      "mechanism": "",
      "points": "",
      "images": [],
      "youtubeId": ""
    }
  ],
  "site": {
    "title": "物理部無線班",
    "english": "BUTSUMU CLUB",
    "tagline": "キャッチコピー",
    "intro": "入力してください",
    "roomIntro": "ふたつの部屋から、\n作品をめぐる。",
    "roomNote": "展示室名・作品の配置は仮のものです。",
    "archiveNote": "作品写真・説明文は準備中です。",
    "about": "動くもの。音を奏でるもの。\n光るもの。遊べるもの。\n\n物理部無線班の文化祭展示を、\nひとつひとつの作品から紹介します。\n\n気になる作品から、その仕組みや\nものづくりの面白さに触れてみてください。",
    "heroImage": "images/architecture.svg",
    "heroAlt": "曲線と光の重なりを表現した抽象的な建築ビジュアル"
  }
};
