'use strict';
const {rooms,exhibits}=window.EXHIBITION_DATA;
const site={title:'物理部無線班',english:'PHYSICS & RADIO CLUB',tagline:'つくる。うごく。\nその先の、不思議へ。',intro:'物理とものづくりの、展示空間。',roomIntro:'ふたつの部屋から、\n作品をめぐる。',roomNote:'展示室名・作品の配置は仮のものです。',archiveNote:'作品写真・説明文は準備中です。',about:'動くもの。音を奏でるもの。\n光るもの。遊べるもの。\n\n物理部無線班の文化祭展示を、\nひとつひとつの作品から紹介します。\n\n気になる作品から、その仕組みや\nものづくりの面白さに触れてみてください。',heroImage:'images/architecture.svg',heroAlt:'曲線と光の重なりを表現した抽象的な建築ビジュアル',...window.EXHIBITION_DATA.site};
document.title=site.title;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=s=>esc(s).replace(/\n/g,'<br>');
const roomUrl=id=>'room.html?id='+encodeURIComponent(id);
const workUrl=slug=>'exhibit.html?slug='+encodeURIComponent(slug);
const asset=src=>{const s=String(src||'');return /^(https?:\/\/|data:image\/)/.test(s)?s:s.replace(/^\/+/, '')};
const img=(src,alt,extra='')=>`<img src="${esc(asset(src))}" alt="${esc(alt)}" ${extra}>`;
const list=id=>exhibits.filter(w=>w.roomId===id).sort((a,b)=>a.order-b.order);
const imagesFor=w=>w.images?.length?w.images:[{src:`images/placeholder-${Number(w.number)%3}.svg`,alt:w.name+'の写真準備中を示す抽象ビジュアル',caption:'作品写真準備中 / ABSTRACT PLACEHOLDER'}];
const nav=`<a href="index.html">HOME</a><a href="index.html#rooms">EXHIBITION ROOMS</a><a href="index.html#about">ABOUT</a>`;
const header=`<a class="skip-link" href="#main">本文へ移動</a><header class="site-header"><a class="brand" href="index.html" aria-label="${esc(site.title)} ホーム"><span class="brand-mark" aria-hidden="true">∿</span><span>${esc(site.title)}<small>${esc(site.english)}</small></span></a><nav class="desktop-nav" aria-label="メインナビゲーション">${nav}</nav><div class="mobile-nav"><button class="menu-button" id="open-menu" aria-haspopup="dialog">MENU ☰</button></div></header><dialog class="mobile-sheet" id="menu" aria-label="メニュー"><button class="close-menu" id="close-menu">閉じる ×</button><p>${esc(site.title)}</p><nav>${nav}</nav></dialog>`;
const footer=`<footer class="site-footer"><a href="index.html">${esc(site.title)}<small>${esc(site.english)}</small></a><p>文化祭 作品アーカイブ</p><span>© ${esc(site.english)}</span></footer>`;
const crumb=items=>`<nav class="breadcrumb" aria-label="パンくずリスト"><ol><li><a href="index.html">HOME</a></li>${items.map(x=>`<li>${x.url?`<a href="${esc(x.url)}">${esc(x.name)}</a>`:`<span aria-current="page">${esc(x.name)}</span>`}</li>`).join('')}</ol></nav>`;
function home(){return `<main id="main"><section class="hero"><div class="hero-heading"><div><p class="eyebrow red">CULTURAL FESTIVAL / WORKS ARCHIVE</p><h1>${esc(site.title)}</h1><p class="hero-english">${esc(site.english)}</p></div><p class="hero-note">${lines(site.tagline)}</p></div><div class="hero-visual">${img(site.heroImage,site.heroAlt)}<div class="hero-vertical">A PLACE FOR CURIOSITY.</div><a href="#rooms" class="hero-entry"><span>作品に出会う</span><span>EXHIBITION ROOMS <b>↓</b></span></a><span class="visual-caption">${site.heroImage==='images/architecture.svg'?'ABSTRACT ARCHITECTURE — 01':'MAIN VISUAL'}</span></div><div class="hero-bottom"><span>${esc(site.intro)}</span><span>${String(rooms.length).padStart(2,'0')} ROOMS <i></i> ${exhibits.length} WORKS</span></div></section><section class="rooms-section container" id="rooms"><div class="section-heading"><div><p class="eyebrow red">EXHIBITION ROOMS</p><h2>展示室</h2></div><p>${lines(site.roomIntro)}</p></div><div class="room-grid">${rooms.map((r,i)=>`<div class="reveal"><a class="room-card" href="${roomUrl(r.id)}"><div class="room-image">${img(r.image,r.alt,'loading="lazy"')}<span class="room-digit">${String(i+1).padStart(2,'0')}</span><span class="room-image-label">${r.image.startsWith('images/room-')?'ABSTRACT SPACE':'EXHIBITION ROOM'}</span></div><div class="room-title"><div><span class="eyebrow">${esc(r.label)} <i></i> ${list(r.id).length} WORKS</span><h3>${esc(r.name)}</h3></div><span class="circle-arrow">↗</span></div><p class="room-preview">${list(r.id).slice(0,3).map(w=>esc(w.name)).join(' / ')} ほか</p><span class="text-link">展示室に入る →</span></a></div>`).join('')}</div>${site.roomNote?`<p class="section-note">${esc(site.roomNote)}</p>`:''}</section><section class="about-section" id="about"><div class="container about-grid"><div><p class="eyebrow red">ABOUT US</p><h2>${esc(site.title)}<br>について</h2></div><div class="about-copy">${site.about.split(/\n\s*\n/).map((p,i)=>`<p${i>1?' class="muted"':''}>${lines(p)}</p>`).join('')}</div><span class="about-number" aria-hidden="true">∿</span></div></section></main>`}
function card(w){const image=imagesFor(w)[0];return `<article class="work-card reveal"><a class="work-image" href="${workUrl(w.slug)}" aria-label="${esc(w.name)}の詳細を見る">${img(image.src,image.alt,'loading="lazy"')}<span class="image-index">${esc(w.number)}</span>${!w.images?.length?'<span class="placeholder-label">PHOTOGRAPH COMING SOON</span>':''}</a><div class="work-meta">WORK ${esc(w.number)}</div><h2><a href="${workUrl(w.slug)}">${esc(w.name)}</a></h2>${w.summary?`<p>${esc(w.summary)}</p>`:''}<a class="text-link" href="${workUrl(w.slug)}">この展示について →</a></article>`}
function room(r){document.title=r.name+' | '+site.title;const works=list(r.id),other=rooms.find(x=>x.id!==r.id);return `<main id="main" class="container inner-page">${crumb([{name:r.name}])}<header class="page-heading"><div><p class="eyebrow red">${esc(r.label)} / EXHIBITION ROOM</p><h1>${esc(r.name)}</h1></div><p class="count"><strong>${String(works.length).padStart(2,'0')}</strong> WORKS</p></header><div class="archive-intro"><p>作品を選んで、展示の詳細をご覧ください。</p>${site.archiveNote?`<span>${esc(site.archiveNote)}</span>`:''}</div><div class="works-grid">${works.map(card).join('')}</div><nav class="bottom-nav"><a class="text-link" href="index.html">← トップページへ</a>${other?`<a class="next-room" href="${roomUrl(other.id)}"><span class="eyebrow">${esc(other.label)}</span><span>${esc(other.name)}へ →</span></a>`:''}</nav></main>`}
let currentWork=null;
function detail(w){const r=rooms.find(r=>r.id===w.roomId);if(!r)return notFound();currentWork=w;document.title=w.name+' | '+site.title;return `<main id="main" class="container inner-page detail-page">${crumb([{name:r.name,url:roomUrl(r.id)},{name:w.name}])}<header class="detail-heading"><p class="eyebrow red">WORK ${esc(w.number)} <i></i> ${esc(r.label)}</p><h1>${esc(w.name)}</h1><a class="muted" href="${roomUrl(r.id)}">${esc(r.name)}</a></header><div class="gallery"><button class="gallery-main" id="open-image" aria-label="${esc(w.name)}の画像を拡大"><img id="main-image" alt=""><span class="zoom-label">画像を拡大 ＋</span>${!w.images?.length?'<span class="gallery-placeholder">PHOTOGRAPH COMING SOON<br><small>作品写真準備中</small></span>':''}</button><div class="gallery-caption"><p id="caption"></p><span id="image-count"></span></div><div class="thumbnails" id="thumbnails"></div></div><dialog class="lightbox" id="lightbox" aria-label="${esc(w.name)}の拡大画像"><button class="lightbox-close" id="close-image">閉じる ×</button><img id="large-image" alt=""><div class="gallery-controls" id="image-controls"><button id="previous-image">前の画像</button><button id="next-image">次の画像</button></div></dialog><section class="work-description"><div><p class="eyebrow red">ABOUT THIS WORK</p><h2>この展示について</h2></div><div class="prose"><section><h3>作品の概要</h3><p>${esc(w.summary||'説明文準備中')}</p></section><section><h3>作品の仕組み・制作のポイント</h3><p>${esc(w.mechanism||'説明文準備中')}</p>${w.points?`<p>${esc(w.points)}</p>`:''}</section>${/^[\w-]{11}$/.test(w.youtubeId||'')?`<section><h3>作品の動画</h3><iframe class="video" title="${esc(w.name)}の紹介動画" src="https://www.youtube-nocookie.com/embed/${esc(w.youtubeId)}" loading="lazy" allowfullscreen></iframe></section>`:''}</div></section><nav class="bottom-nav"><a class="text-link" href="${roomUrl(r.id)}">← ${esc(r.name)}に戻る</a><a class="text-link" href="index.html#rooms">すべての展示室</a></nav></main>`}
function notFound(){document.title='展示が見つかりません | '+site.title;return `<main id="main" class="not-found container"><p class="eyebrow red">404 / NOT FOUND</p><h1>この展示は<br>見つかりませんでした。</h1><p>URLをご確認いただくか、展示室から作品をお探しください。</p><a class="text-link" href="index.html#rooms">展示室を見る →</a></main>`}
const filename=location.pathname.split('/').pop(),params=new URLSearchParams(location.search);let content;
if(filename==='room.html'){const r=rooms.find(r=>r.id===params.get('id'));content=r?room(r):notFound()}
else if(filename==='exhibit.html'){const w=exhibits.find(w=>w.slug===params.get('slug'));content=w?detail(w):notFound()}
else content=filename==='404.html'?notFound():home();
document.getElementById('app').innerHTML=header+content+footer;
const menu=document.getElementById('menu');document.getElementById('open-menu').onclick=()=>menu.showModal();document.getElementById('close-menu').onclick=()=>menu.close();menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.close()));
if(currentWork){let index=0;const images=imagesFor(currentWork),dialog=document.getElementById('lightbox');const thumbs=document.getElementById('thumbnails');
function update(){const image=images[index];for(const id of ['main-image','large-image']){const el=document.getElementById(id);el.src=asset(image.src);el.alt=image.alt||currentWork.name}document.getElementById('caption').textContent=image.caption||image.alt||'';document.getElementById('image-count').textContent=`${index+1} / ${images.length}`;thumbs.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)))}
if(images.length>1)images.forEach((image,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`画像${i+1}を表示`);b.innerHTML=img(image.src,image.alt);b.onclick=()=>{index=i;update()};thumbs.append(b)});else document.getElementById('image-controls').hidden=true;
document.getElementById('open-image').onclick=()=>dialog.showModal();document.getElementById('close-image').onclick=()=>dialog.close();document.getElementById('previous-image').onclick=()=>{index=(index+images.length-1)%images.length;update()};document.getElementById('next-image').onclick=()=>{index=(index+1)%images.length;update()};dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')document.getElementById('previous-image').click();if(e.key==='ArrowRight')document.getElementById('next-image').click()});update()}
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('will-reveal');observer.observe(el)})}

